// Legacy URLs reported as invalid and intentionally kept out of the public site.
export const invalidLegacyProjectSlugs = new Set([
  "bonsai-spirit-logo",
  "precision-pharma-logo",
  "james-laura-wedding-website-development",
  "anemone-wordpress-quick-website-development",
  "adelie-pebbles-logo",
  "partake-foods-shopify-store-development",
  "david-coffey-wordpress-website",
  "nyc-valet-parking-logo",
  "infinity-logistics-logo",
  "jk-crowe-logo",
  "green-thumb-logo",
  "cafe-34-logo",
  "cowboy-shopify-store-development",
  "anybotics-wordpress-store-development",
  "dropps-shopify-store-development",
  "firefly-logo",
  "gc-remedial-logo",
  "visual-soldiers-wordpress-website",
  "debra-smalley-wordpress-website-for-real-estate",
  "oskar-gydells-wordpress-woocommerce-website",
  "3d-mania-wordpress-woocommerce-website",
  "brew-house-logo",
  "saie-shopify-store-development",
  "360-inspex-logo",
  "ak-logo",
  "anchor-arms-logo",
  "artisanalley-logo",
  "athletic-club-logo",
  "autozone-special-logo",
  "bang-logo",
  "beehive-homes-logo",
  "blue-paradise-logo",
  "bonafide-distributions-logo",
  "business-profit-logo",
  "byte-craft-logo",
  "candice-hunter-logo-2",
  "catalyst-logo",
  "cfn-logo",
  "cool-fusion-logo",
  "country-life-logo",
  "crane-logo",
  "cycle-savvy-logo",
  "dc-logo",
  "exponential-logo",
  "free-spirit-logo",
  "free-spirit-logo-2",
  "fresh-bite-logo",
  "fresh-food-logo",
  "fresh-fusion-logo",
  "fulconstruction-logo",
  "gator-logo",
  "glam-glow-logo",
  "globalminds-logo",
  "golden-integrity-logo",
  "healthy-hour-logo",
  "high-pay-home-logo",
  "ibixx-logo",
  "i-learn-technologies-logo",
  "institutional-coaching-logo",
  "it-club-logo",
  "joco-cups-wordpress-woocommerce-website",
  "league-one-logo",
  "legal-happy-hour-logo",
  "logo",
  "louise-davies-logo",
  "lucas-car-logo",
  "lucas-cars-logo",
  "marysville-logo",
  "mici-logo",
  "midwest-logo",
  "m-logo",
  "moreyat-logo",
  "music-synergy-logo",
  "my-chiropractor",
  "nenix-logo",
  "pet-assess-logo",
  "petpals-logo",
  "planetva-logo",
  "platinum-logo",
  "purrfect-groom-logo",
  "revolution-dance-logo",
  "rhino-parts-logo",
  "saguaro-corners-logo",
  "savory-spice-logo",
  "six-minute-webinar-logo",
  "smart-solution-logo",
  "sokoglam-shopify-store-development",
  "solar-logo",
  "sparkle-tech-logo",
  "star-light-logo",
  "summit-strategies-logo",
  "synergy-appliances-logo",
  "tasty-trove-logo",
  "technova-logo",
  "the-business-logo",
  "the-scarlet-bee",
  "the-vitality-logo",
  "tinker-tech-logo",
  "value-safety-logo",
  "vector-labs-logo",
  "veisley-logo",
  "village-market-logo",
  "viva-logo",
  "volt-plus-logo",
  "westbourne-shopify-website-development",
  "wh-data-logo",
  "womankind-fitness-logo",
  "women-empowered-logo",
  "yoga-high-logo",
  "you-summit-logo",
]);

export const getProjectSlugFromHref = (href = "") => {
  try {
    const pathname = new URL(
      href,
      "https://www.webfoundersusa.com",
    ).pathname;
    const segments = pathname.split("/").filter(Boolean);
    const projectsIndex = segments.indexOf("projects");
    return projectsIndex >= 0 ? segments[projectsIndex + 1] || "" : "";
  } catch {
    return "";
  }
};

export const isInvalidLegacyProjectHref = (href = "") =>
  invalidLegacyProjectSlugs.has(getProjectSlugFromHref(href));
