// Legacy URLs reported as invalid and intentionally kept out of the public site.
export const invalidLegacyProjectSlugs = new Set([
  "bonsai-spirit-logo",
  "precision-pharma-logo",
  "james-laura-wedding-website-development",
  "anemone-wordpress-quick-website-development",
  "adelie-pebbles-logo",
  "partake-foods-shopify-store-development",
  "david-coffey-wordpress-website",
  "nyc-valet-parking-logo",
  "infinity-logistics-logo",
  "jk-crowe-logo",
  "green-thumb-logo",
  "cafe-34-logo",
  "cowboy-shopify-store-development",
  "anybotics-wordpress-store-development",
  "dropps-shopify-store-development",
  "firefly-logo",
  "gc-remedial-logo",
  "visual-soldiers-wordpress-website",
  "debra-smalley-wordpress-website-for-real-estate",
  "oskar-gydells-wordpress-woocommerce-website",
  "3d-mania-wordpress-woocommerce-website",
  "brew-house-logo",
  "saie-shopify-store-development",
]);
