// /lib/fakeData/pricingData.js

export const pricingData = [
  {
    id: 1,
    plan_name: "Startup Website Package",
    category: "Website Design",
    price: "199",
    old_price: "299",
    services: [
      "2 Stock Photos",
      "3 Page Website",
      "3 Banner Design",
      "1 jQuery Slider Banner",
      "FREE Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *",
      "Mobile Responsive will be Additional $99*",
      "CMS will be Additional $149*"
    ],
  },
  {
    id: 2,
    plan_name: "PROFESSIONAL WEBSITE PACKAGE",
    category: "Website Design",
    price: "599",
    old_price: "799",
    services: [
      "6 Unique Pages Website",
      "5 Stock images",
      "5 Banner Designs",
      "1 jQuery Slider Banner",
      "FREE Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "Mobile Responsive",
      "CMS (Content Management System)",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *",
    ],
  },
  {
    id: 3,
    plan_name: "Elite WEBSITE PACKAGE",
    category: "Website Design",
    price: "875",
    old_price: "1250",
    services: [
      "Upto 10 Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Mobile Responsive",
      "Online Reservation/Appointment Tool (Optional)",
      "Online Payment Integration (Optional)",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Special Hover Effects",
      "Newsletter Subscription (Optional)",
      "Newsfeed Integration",
      "Social Media Integration",
      "Search Engine Submission",
      "6 Stock Photos",
      "3 Unique Banner Design",
      "1 jQuery Slider Banner",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *"
    ],
  },
  {
    id: 4,
    plan_name: "Silver Website PACKAGE",
    category: "Website Design",
    price: "1120",
    old_price: "1600",
    services: [
      "15 Pages Website",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Custom WP (or) Custom PHP Development",
      "1 jQuery Slider Banner",
      "Up to 10 Custom Made Banner Designs",
      "8 Stock Images",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System (CMS)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional) ",
      "Mobile Responsive",
      "FREE 5 Years Domain Name",
      "Free Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry Specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *",

    ],
  },
  {
    id: 5,
    plan_name: "CORPORATE WEBSITE PACKAGE",
    category: "Website ",
    price: "2599",
    old_price: "398",
    services: [
      "Unlimited Pages Website Design",
      "Custom, Mobile, Interactive, Dynamic & High-end Design",
      "Customizable WordPress (or) PHP Development",
      "Interactive Sliding Banners",
      "Up to 15 Custom Made Banner Designs",
      "15 Stock Images"
    ],
  },
  ,
  {
    id: 6,
    plan_name: "CORPORATE WEBSITE PACKAGE",
    category: "E-Commerce",
    price: "2599",
    old_price: "398",
    services: [
      "Unlimited Pages Website Design",
      "Custom, Mobile, Interactive, Dynamic & High-end Design",
      "Customizable WordPress (or) PHP Development",
      "Interactive Sliding Banners",
      "Up to 15 Custom Made Banner Designs",
      "15 Stock Images"
    ],
  },
  // Add other category packages below as needed:
  // Example:
  // {
  //   id: 6,
  //   plan_name: "BASIC E-COMMERCE PACKAGE",
  //   category: "E-Commerce",
  //   price: "999",
  //   services: [ ... ],
  // },
];
