// /lib/fakeData/pricingData.js

export const pricingData = [
  {
    id: 1,
    plan_name: "Startup Website",
    category: "Website Design",
    price: "199",
    old_price: "299",
    services: [
      "2 Stock Photos",
      "3 Page Website",
      "3 Banner Design",
      "1 jQuery Slider Banner",
      "FREE Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *",
      "Mobile Responsive will be Additional $99*",
      "CMS will be Additional $149*"
    ],
  },
  {
    id: 2,
    plan_name: "PROFESSIONAL WEBSITE",
    category: "Website Design",
    price: "599",
    old_price: "799",
    services: [
      "6 Unique Pages Website",
      "5 Stock images",
      "5 Banner Designs",
      "1 jQuery Slider Banner",
      "FREE Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "Mobile Responsive",
      "CMS (Content Management System)",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *",
    ],
  },
  {
    id: 3,
    plan_name: "Elite WEBSITE",
    category: "Website Design",
    price: "875",
    old_price: "1250",
    services: [
      "Upto 10 Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Mobile Responsive",
      "Online Reservation/Appointment Tool (Optional)",
      "Online Payment Integration (Optional)",
      "Custom Forms",
      "Lead Capturing Forms (Optional)",
      "Special Hover Effects",
      "Newsletter Subscription (Optional)",
      "Newsfeed Integration",
      "Social Media Integration",
      "Search Engine Submission",
      "6 Stock Photos",
      "3 Unique Banner Design",
      "1 jQuery Slider Banner",
      "Complete W3C Certified HTML",
      "48 to 72 hours TAT",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *"
    ],
  },
  {
    id: 4,
    plan_name: "Silver Website",
    category: "Website Design",
    price: "1120",
    old_price: "1600",
    services: [
      "15 Pages Website",
      "Custom Made, Interactive, Dynamic & High End Design",
      "Custom WP (or) Custom PHP Development",
      "1 jQuery Slider Banner",
      "Up to 10 Custom Made Banner Designs",
      "8 Stock Images",
      "Unlimited Revisions",
      "Special Hover Effects",
      "Content Management System (CMS)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar",
      "Live Feeds of Social Networks integration (Optional) ",
      "Mobile Responsive",
      "FREE 5 Years Domain Name",
      "Free Google Friendly Sitemap",
      "Search Engine Submission",
      "Complete W3C Certified HTML",
      "Industry Specified Team of Expert Designers and Developers",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *",

    ],
  },
  {
    id: 5,
    plan_name: "Beginners E-Commerce",
    category: "E-Commerce",
    price: "999",
    old_price: "1700",
    services: [
      "Upto 15 Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Content Management System (CMS)",
      "Mobile Responsive",
      "Easy Product Search",
      "Product Reviews",
      "Up To 100 Products",
      "Up To 7 Categories",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Sales & Inventory Management",
      "Jquery Slider",
      "Free Google Friendly Sitemap",
      "FREE 1 Years Hosting",
      "Custom Email Addresses",
      "Complete W3C Certified HTML",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee"
    ],
  },
  {
    id: 6,
    plan_name: "Corporate E-Commerce",
    category: "E-Commerce",
    price: "1750",
    old_price: "2500",
    services: [
      "Unlimited Unique Pages Website",
      "Conceptual and Dynamic Website",
      "Content Management System (CMS)",
      "Mobile Responsive",
      "Easy Product Search",
      "Product Reviews",
      "Unlimited Products",
      "Unlimited Categories",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Sales & Inventory Management",
      "Jquery Slider",
      "Free Google Friendly Sitemap",
      "FREE 3 Years Hosting",
      "Custom Email Addresses",
      "Complete W3C Certified HTML",
      "Facebook Page Design",
      "Twitter Page Design",
      "YouTube Page Design",
      "Instagram Page Design",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee"
    ],
  },
  {
    id: 7,
    plan_name: "Elite E-Commerce",
    category: "E-Commerce",
    price: "2450",
    old_price: "3500",
    services: [
      "UNLIMITED Logo Design Concepts",
      "By 6 Award Winning Designers",
      "Icon Design",
      "UNLIMITED Revisions",
      "Print Media",
      "Stationary Design (BusinessCard,Letterhead & Envelope)",
      "Invoice Design, Email Signature",
      "Bi-Fold Brochure (OR) 2 Sided Flyer Design",
      "Product Catalog Design",
      "Sign age Design (OR) Label Design",
      "T-Shirt Design (OR) Car Wrap Design",
      "Website",
      "E-Commerce Store Design",
      "Product Detail Page Design",
      "Unique Banner Slider",
      "Featured Products Showcase",
      "Full Shopping Cart Integration",
      "Unlimited Products",
      "Unlimited Categories",
      "Product Rating & Reviews",
      "Easy Product Search",
      "Payment Gateway Integration",
      "Multi-currency Support",
      "Content Management System",
      "Cutomer Log-in Area",
      "Mobile Responsive",
      "Social Media Plugins Integration",
      "Tell a Friend Feature",
      "Social Media Pages",
      "Facebook , Twitter, YouTube, Google+ & Pinterest Page Designs",
      "Value Added Services",
      "Dedicated Account Manager",
      "Unlimited Revisions",
      "All Final File Formats",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee *"
    ],
  },
  {
    id: 8,
    plan_name: "Basic",
    category: "Logo",
    price: "42",
    old_price: "60",
    services: [
      "2 Custom Logo Design Concepts",
      "1 Dedicated Designer",
      "4 REVISIONS",
      "48 to 72 hours TAT",
      "100% Unique Design Guarantee",
      "100% Satisfaction Guarantee",
      "100% Ownership Rights *",
      "100% Money Back Guarantee *",
    ],
  },
  {
    id: 9,
    plan_name: "Startup",
    category: "Logo",
    price: "73",
    old_price: "105",
    services: [
      "5 Custom Logo Design Concepts",
      "By 2 Designers",
      "UNLIMITED Revisions",
      "UNLIMITED Revisions",
      "48 to 72 hours TAT",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Ownership Rights *",
      "100% Money Back Guarantee *"
    ],
  },
  {
    id: 10,
    plan_name: "Professional",
    category: "Logo",
    price: "115",
    old_price: "165",
    services: [
      "UNLIMITED Logo Design Concepts",
      "By 4 Designers",
      "UNLIMITED Revisions",
      "UNLIMITED Revisions",
      "Stationary Design (Business Card, Letterhead, Envelope)",
      "48 to 72 hours TAT",
      "FREE MS Word Letterhead",
      "All Final Files Format (AI, PSD, EPS, PNG, GIF, jpeg, PDF)",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Ownership Rights *",
      "100% Money Back Guarantee *"
    ],
  },
  {
    id: 11,
    plan_name: "StartUp Plan",
    category: "SEO",
    price: "350",
    old_price: "500",
    services: [
      "Better Packages, Better Prices",
      "Domain Overview",
      "Website Audit",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "15 selected Keyword Targeting",
      "15 page Keyword Targeting",
      "ON Page Optimization",
      "Meta tag creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of anchors",
      "Call To Action Plan",
      "Creation of Sitemaps",
      "Creation of Robots.txt",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ’s",
      "Link Building",
      "Directory Submission",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support"
    ],
  },

  {
    id: 12,
    plan_name: "Scaling Plan",
    category: "SEO",
    price: "700",
    old_price: "1000",
    services: [
      "Prior Analysis",
      "Domain Overview",
      "Website Audit",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "30 selected Keyword Targeting",
      "ON Page Optimization",
      "Meta tag creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of anchors tag",
      "Inclusion of anchors Indexing Modifications",
      "Creation of Sitemaps",
      "Creation of Robots.txt",
      "Google places inclusions",
      "Call To Action Plan",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ’s",
      "Link Building",
      "Directory Submission",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support"
    ],
  },

   {
    id: 13,
    plan_name: "Venture Plan",
    category: "SEO",
    price: "1120",
    old_price: "1620",
    services: [
      "Prior Analysis",
      "Domain Overview",
      "Website Audit",
      "Business Analysis",
      "Consumer Analysis",
      "Competitor Analysis",
      "70 selected Keyword Targeting",
      "50selected Keyword Targeting",
      "ON Page Optimization",
      "Meta tag creation",
      "Keyword Optimization",
      "Image Optimization",
      "Inclusion of anchors tag",
      "Inclusion of anchors Indexing Modifications",
      "Creation of Sitemaps",
      "Creation of Robots.txt",
      "Google places inclusions",
      "Call To Action Plan",
      "Off Page Optimization",
      "Social Bookmarking",
      "Slide Share Marketing",
      "Forums/FAQ’s",
      "Link Building",
      "Directory Submission",
      "Local Business Listings",
      "Reporting",
      "Monthly Reporting",
      "Recommendation",
      "Email Support",
      "Phone Support"
    ],
  },

  {
    id: 14,
    plan_name: "Stationary ",
    category: "Branding",
    price: "99",
    old_price: "142",
    services: [
      "1 Business Card Design",
      "1 Letterhead Design",
      "1 Envelope Design",
      "Dedicated Designer",
      "3 Design Revisions",
      "Turnaround Time 24 - 48 Hours",
      "Features:",
      "100% Satisfaction Guaranteed",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "All Final File Formats"
    ],
  },

  {
    id: 15,
    plan_name: "Brochur/Flyer",
    category: "Branding",
    price: "149",
    old_price: "214",
    services: [
      "2 Design Concepts (Trifold / Bi-fold)",
      "Dedicated Designer",
      "Dedicated Account Manager",
      "Unlimited Revisions",
      "Turnaround Time - 48 - 72 Hours",
      "100% Satisfaction Guaranteed",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "All Final File Formats"
    ],
  },

  {
    id: 16,
    plan_name: "Poster Design",
    category: "Branding",
    price: "295",
    old_price: "420",
    services: [
      "1 Unique Design",
      "3 Design Concepts",
      "Dedicated Designer",
      "2 Design Revisions",
      "Turnaround Time - 48 - 72 Hours",
      "100% Satisfaction Guaranteed",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
      "All Final File Formats"
    ],
  },

  {
    id: 17,
    plan_name: "Basic",
    category: "SMM",
    price: "699",
    old_price: "999",
    services: [
      "12/Month Unique Social Media Content Postingn",
      "Social Media Analysis",
      "Page Optimization",
      "Social Media Marketing Plan",
      "Post Design Scheduling",
      "Profile Keyword Optimization - 3 Keywords",
      "Performance Report",
      "2 Platforms"
    ],
  },

   {
    id: 18,
    plan_name: "Standard",
    category: "SMM",
    price: "1050",
    old_price: "1500",
    services: [
      "20/Month Unique Social Media Content Posting",
      "Competitor Analysis",
      "Community Management",
      "Page Moderation",
      "Social Media Strategy",
      "Page Monitoring & Responding",
      "Social Media Analysis",
      "Page Optimization",
      "Social Media Marketing Plan",
      "Post Design Scheduling",
      "Profile Keyword Optimization - 6 Keywords",
      "Performance Report",
      "4 Platforms"
    ],
  },

  {
    id: 19,
    plan_name: "Prime",
    category: "SMM",
    price: "1225",
    old_price: "1750",
    services: [
      "40/Month Unique Social Media Content Posting",
      "Competitor Analysis",
      "Community Management",
      "Page Moderation",
      "Page Monitoring & Responding",
      "Social Media Analysis",
      "Page Optimization",
      "Social Media Marketing Plan",
      "Post Design Scheduling",
      "Profile Keyword Optimization - 8 Keywords",
      "Performance Report",
      "Unlimited Platforms"
    ],
  },

  {
    id: 20,
    plan_name: "3 Months",
    category: "Maintenance",
    price: "199",
    old_price: "285",
    services: [
      "BackupBuddy",
      "UpDraftPlus",
      "Duplicator",
      "BackWPup",
      "Wordfence Security",
      "iThemes Security",
      "All In One WP Security & Firewall",
      "Sucuri Security",
      "Uptrends",
      "Pingdom",
      "GTmetrix",
      "Google Analytics",
      "Google Analytics for WordPress",
      "Google Analytics Dashboard for WP",
      "hrefs"
    ],
  },

  {
    id: 21,
    plan_name: "6 Months",
    category: "Maintenance",
    price: "299",
    old_price: "428",
    services: [
      "BackupBuddy",
      "UpDraftPlus",
      "Duplicator",
      "BackWPup",
      "Wordfence Security",
      "iThemes Security",
      "All In One WP Security & Firewall",
      "Sucuri Security",
      "Uptrends",
      "Pingdom",
      "GTmetrix",
      "Google Analytics",
      "Google Analytics for WordPress",
      "Google Analytics Dashboard for WP",
      "hrefs"
    ],
  },

  {
    id: 22,
    plan_name: "12 Months",
    category: "Maintenance",
    price: "499 ",
    old_price: "712",
    services: [
      "BackupBuddy",
      "UpDraftPlus",
      "Duplicator",
      "BackWPup",
      "Wordfence Security",
      "iThemes Security",
      "All In One WP Security & Firewall",
      "Sucuri Security",
      "Uptrends",
      "Pingdom",
      "GTmetrix",
      "Google Analytics",
      "Google Analytics for WordPress",
      "Google Analytics Dashboard for WP",
      "hrefs"
    ],
  },

  {
    id: 23,
    plan_name: "Basic Video Package",
    category: "Video Animation",
    price: "199 ",
    old_price: " 285",
    services: [
      "Script",
      "Storyboard & Characters",
      "Voiceover",
      "Animation & SFX",
      "Finalized & Published",
    ],
  },

  {
    id: 24,
    plan_name: "Basic Plus  Video Package",
    category: "Video Animation",
    price: "299",
    old_price: " 428",
    services: [
      "Script",
      "Storyboard & Characters",
      "Voiceover",
      "Animation & SFX",
      "Finalized & Published",
    ],
  },

  {
    id: 25,
    plan_name: "Classic Plus  Video Package",
    category: "Video Animation",
    price: "499",
    old_price: "712",
    services: [
      "Script",
      "Storyboard & Characters",
      "Voiceover",
      "Animation & SFX",
      "Finalized & Published",
    ],
  },
];

